"""update user conversation relation

Revision ID: 4eece8fe2aaf
Revises: 48e656854b5b
Create Date: 2026-08-08 18:38:13.013817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eece8fe2aaf'
down_revision: Union[str, Sequence[str], None] = '48e656854b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)
    # ### end Alembic commands ###
