"""update user conversation relation

Revision ID: aa09ddaac9f8
Revises: ca8163303959
Create Date: 2026-08-09 23:33:45.642740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa09ddaac9f8'
down_revision: Union[str, Sequence[str], None] = 'ca8163303959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_file', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('knowledge_file', sa.Column('storage_filename', sa.String(length=255), nullable=True))
    op.drop_column('knowledge_file', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_file', sa.Column('filename', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('knowledge_file', 'storage_filename')
    op.drop_column('knowledge_file', 'original_filename')
    # ### end Alembic commands ###
